kind: Service
apiVersion: v1
metadata:
  name: argo-server
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
  - protocol: TCP
    port: 443
  type: NodePort