kind: Service
apiVersion: v1
metadata:
  name: argocd-server
spec:
  selector:
    app: myapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30001
  - name: https
    protocol: TCP
    port: 443
  type: NodePort