apiVersion: v1
kind: Secret
metadata:
  name: secret-dbt
data:
  profile.yml: ZGJ0X2ZpbmFuY2lhbDoKICBvdXRwdXRzOgoKICAgIGRldjoKICAgICAgdHlwZTogcG9zdGdyZXMKICAgICAgdGhyZWFkczogNAogICAgICBob3N0OiB0aW1lc2NhbGVkYi5mZHAuc3ZjLmNsdXN0ZXIubG9jYWwKICAgICAgcG9ydDogNTQzMgogICAgICB1c2VyOiBmZHAKICAgICAgcGFzczogZmRwCiAgICAgIGRibmFtZTogZmluYW5jaWFsX2RhdGEKICAgICAgc2NoZW1hOiBmaW5hbmNpYWxfcmF3CgogICAgcHJvZDoKICAgICAgdHlwZTogcG9zdGdyZXMKICAgICAgdGhyZWFkczogNAogICAgICBob3N0OiB0aW1lc2NhbGVkYi5mZHAuc3ZjLmNsdXN0ZXIubG9jYWwKICAgICAgcG9ydDogNTQzMgogICAgICB1c2VyOiBmZHAKICAgICAgcGFzczogZmRwCiAgICAgIGRibmFtZTogZmluYW5jaWFsX2RhdGEKICAgICAgc2NoZW1hOiBmaW5h
  user.yml: aWQ6IDVlOGIyZTNiLWM0NjMtNDZjMS05MzQzLWZlNDY5ODA3NzAzZAo=