apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vietcheems/fdp-helm-chart
    targetRevision: HEAD
    path: superset
    helm:
      releaseName: superset
      valueFiles:
      - myvalues.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fdp
  syncPolicy:
    automated: {}